### PR TITLE
UI-2261: Provide account name to connectivity.create

### PR DESCRIPTION
**Pull request by dsau**

### CODE REVIEW

**Comment by dsau** [comment]
Not exactly sure if the account name is the correct data to be passing here?

**Comment by JRMaitre** [comment]
Hey thank you for the pull request, unfortunately I won't merge it as it would only be a temp fix. This bug (name missing) was introduced by a change in the schema of the back-end, they reverted this change to require a name in 3.22.58 so the UI will be able to work normally without any change if you upgrade Kazoo to that version.

**Comment by dsau** [comment]
Ah, sorry! I just installed kazoo yesterday and came up against the issue, saw the ticket open in Jira and thought I'd take a look. Serves me right for taking the easy avenue (RPM).

Cheers.

**Comment by JRMaitre** [comment]
No worries at all :)

**Pull request closed without merging**
